### PR TITLE
fixed "UnicodeDecodeError: 'ascii' codec..."

### PR DESCRIPTION
**Pull request by bashu**
can you upload bugfix release on PyPi

### CODE REVIEW

**Comment by idlesign** [comment]
Hm. Do we have unicode symbols in README?
I'd probably check it in a week.

**Comment by bashu** [comment]
well I got this:
```python
  Running setup.py (path:/home/vagrant/.virtualenv/build/django-sitemetrics/setup.py) egg_info for package django-sitemetrics
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/vagrant/.virtualenv/build/django-sitemetrics/setup.py", line 7, in <module>
        readme = f.read()
      File "/home/vagrant/.virtualenv/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1005: ordinal not in range(128)
```

**Comment by idlesign** [comment]
So I see. There are those emdashes in README and your venv tries to use ascii as sytem defaults.
We'd apply both fixes, and make a new release today.

**Comment by idlesign** [comment]
v0.5.1 released.

**Pull request merged**
